# Git

`git init` - инициализировать репозиторий

`git add .` - добавить все файлы к отслеживанию

`git commit -m "commit message"` - сделать коммит с названием commit message

`git push origin master` - сделать пуш в удаленный репозиторий origin в ветку master

`git pull` - подтянуть изменения

`git branch new-feature` - сделать ветку new-feature

`git checkout new-feature` - перейти на ветку new-feature

`git log` - посмотреть историю коммитов

`git log --all --decorate --oneline --graph` - посмотреть красивую историю коммитов

`git checkout 978be83` - перейти к коммиту 978be83

При создании репозитория на github, будут написаны команды как запушить код в первый раз

## Задача

Последовательно сделать следующее:

1. Создать новую папку test_git

2. Инициализировать репозиторий

3. Сделать текстовый файл 1.txt, заполнить его по своему усмотрению

4. Сделать коммит

5. Сделать новую ветку second-file, перейти в нее

6. Закоммитить новый файл 2.txt с произвольным содержимым

7. Перейти к master-ветке, проверить, что файл 2.txt остался в другой ветке

8. Замержить ветку second-file в master

# Anaconda

`conda create -n my-environment python=3.8` - создать окружение my-environment с питоном 3.8

`conda activate my-environment` - активировать окружение

`conda deactivate` - деактивировать окружение

`conda install numpy` - установка библиотеки

`conda env export --name my-environment > env.yml` - экспорт всех библиотек в yml файл

`conda env create --file env.yml` - создать окружение из файла env.yml

# Numpy

numpy позволяет оперировать матрицами и векторами

## Установка

В нужном окружении запустить

```
conda install numpy
```

Импортируем библиотеку

In [1]:
import numpy as np

Создаем массив из обычного списка python

In [2]:
test_list = [1, 2, 3]
array = np.array(test_list)
print(array, array.shape, len(array))

[1 2 3] (3,) 3


Генерируем разные массивы

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

Создаем матрицу из списка массива

In [5]:
matrix = [[1, 2, 3], [4, 5, 6]]
np_matrix = np.array(matrix)
print(np_matrix)
print(np_matrix.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


Пример работы reshape

In [6]:
np_matrix.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np_matrix.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [8]:
np_matrix.reshape(-1)

array([1, 2, 3, 4, 5, 6])

## Задача

Сгенерировать вектор из 100 элементов и превратить его в:

- матрицу 10x10
- вектор 1x100
- вектор 100x1

In [9]:
# Ваш код здесь


## Базовые операции

При помощи numpy можно легко делать любые простейшие операции над векторами и матрицами

In [10]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [11]:
a + b

array([20, 31, 42, 53])

In [12]:
b ** 2

array([0, 1, 4, 9])

In [13]:
b < 2

array([ True,  True, False, False])

Выбираем все элементы меньше двух

In [14]:
b[b < 2]

array([0, 1])

In [15]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

Поэлементное произведение

In [16]:
A * B

array([[2, 0],
       [0, 4]])

Произведение матриц

In [17]:
A @ B

array([[5, 4],
       [3, 4]])

In [18]:
A.dot(B) # тоже самое

array([[5, 4],
       [3, 4]])

Транспонирование

In [19]:
B

array([[2, 0],
       [3, 4]])

In [20]:
B.T

array([[2, 3],
       [0, 4]])

## Задача - Решение СЛАУ

$Ax = b$

Функция обратной матрицы - `np.linalg.inv(A)`

In [21]:
A = np.array([
    [3, -2],
    [5, 1]]
)
b = np.array([-6, 3])
# Решение - [0, 3]

In [22]:
# Ваш код здесь


Проверить себя можно при помощи `np.linalg.solve(A, b)` - функция решения СЛАУ

In [23]:
# Ваш код здесь


Создание случайного массива

In [24]:
rand_arr = np.random.uniform(-1, 1, size=(2, 5))
rand_arr

array([[ 0.77281385,  0.64074884,  0.61294663,  0.24135083, -0.2546143 ],
       [ 0.83484931, -0.61158865, -0.92984776,  0.36513642, -0.69238169]])

In [25]:
rand_arr[rand_arr > 0]

array([0.77281385, 0.64074884, 0.61294663, 0.24135083, 0.83484931,
       0.36513642])

Считаем сумму по строкам/столбцам

In [26]:
rand_arr.sum(axis=0)

array([ 1.60766317,  0.02916019, -0.31690112,  0.60648725, -0.94699599])

In [27]:
rand_arr.sum(axis=1)

array([ 2.01324587, -1.03383237])

Находим минимум максимум во всем массиве и по строкам/столбцам

In [28]:
rand_arr.max(), rand_arr.min()

(0.8348493115760991, -0.9298477560221954)

In [29]:
rand_arr.max(axis=0)

array([ 0.83484931,  0.64074884,  0.61294663,  0.36513642, -0.2546143 ])

Также можно применять любые математические операции к массиву

In [30]:
np.sqrt(rand_arr)

/var/folders/70/_zfvbgld4sx4vqvkf7nw5j0m0000gn/T/ipykernel_14648/4099335953.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(rand_arr)


array([[0.87909832, 0.80046789, 0.78290908, 0.4912747 ,        nan],
       [0.91370089,        nan,        nan, 0.60426519,        nan]])

In [31]:
np.exp(rand_arr)

array([[2.16585208, 1.89790157, 1.84586247, 1.27296756, 0.77521544],
       [2.30446677, 0.54248836, 0.39461378, 1.44071053, 0.50038289]])

In [32]:
np.log(rand_arr)

/var/folders/70/_zfvbgld4sx4vqvkf7nw5j0m0000gn/T/ipykernel_14648/772721215.py:1: RuntimeWarning: invalid value encountered in log
  np.log(rand_arr)


array([[-0.25771707, -0.44511772, -0.4894774 , -1.42150366,         nan],
       [-0.18050404,         nan,         nan, -1.00748425,         nan]])

## Задача

Сгенерировать случайную матрицу и посчитать сумму положительных элементов в каждой строке, в каждом столбце.

In [33]:
# Ваш код здесь


## Индексация

Индексация по массивам numpy похожа на индексацию по спискам python, но шире и гибче

Общий синтаксис:

`a[start:stop:step]`

Аргументы можно пропускать, тогда будут взятые аргументы по-умолчанию. Например:

`a[:] == a[0:len(a):1]`

In [34]:
a = np.arange(10)

Выбираем один элемент

In [35]:
a[2]

2

Берем подмассив

In [36]:
a[2:5]

array([2, 3, 4])

Подмассив с заданным шагом

In [37]:
a[:6:2]

array([0, 2, 4])

In [38]:
a[:6:2] = 1000
a

array([1000,    1, 1000,    3, 1000,    5,    6,    7,    8,    9])

In [39]:
a[::-1]

array([   9,    8,    7,    6,    5, 1000,    3, 1000,    1, 1000])

Возьмем матрицу из случайных целых чисел

In [40]:
arr = np.random.randint(1, 5, size=(3, 5))
arr

array([[1, 4, 2, 1, 1],
       [4, 3, 4, 3, 2],
       [1, 2, 4, 2, 4]])

In [41]:
arr[2]

array([1, 2, 4, 2, 4])

По матрицам можно индексироваться отдельно по каждой оси через запятую

Сначала указываем индекс для строк, потом для колонок

In [42]:
a = [1, 2, 3]

a = map(lambda x: x + 2, a)
list(a)

[3, 4, 5]

In [43]:
arr[1:, :2]

array([[4, 3],
       [1, 2]])

In [44]:
arr[::-1, ::2] = 0
arr

array([[0, 4, 0, 1, 0],
       [0, 3, 0, 3, 0],
       [0, 2, 0, 2, 0]])

In [45]:
arr[-1]

array([0, 2, 0, 2, 0])

In [46]:
arr[:, :]

array([[0, 4, 0, 1, 0],
       [0, 3, 0, 3, 0],
       [0, 2, 0, 2, 0]])

Генерируем матрицы

In [47]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Задача

Вывести матрицу из нулей и единиц в шахматном порядке

In [50]:
# Ваш код здесь


## Расширяем массивы

In [51]:
a = np.arange(10)
b = a + 1

In [52]:
a.shape, b.shape

((10,), (10,))

Соединям по горизонтали

In [53]:
np.hstack((a, b)).shape

(20,)

Соединяем по вертикали

In [54]:
np.vstack((a, b)).shape

(2, 10)

In [55]:
np.hstack((a, [1]))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

Расширение массива в numpy происходит путем создания нового массива.

Поэтому если требуется сгенерировать массив, то лучше сделать это через список, а дальше сделать из него массив numpy

In [56]:
%%timeit

a = np.arange(10)
for i in range(1000):
    a = np.hstack((a, 1))
a.shape

3.95 ms ± 32.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [57]:
%%timeit

a = list(range(10))
for i in range(1000):
    a.append(i)
np.array(a).shape

118 µs ± 440 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Сравниваем скорость list и np.array

In [58]:
%%timeit

[i * i for i in range(100000)]

5.09 ms ± 23.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [59]:
%%timeit

a = np.arange(100000)
a * a

58.6 µs ± 166 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Pandas

 Позволяет работать с данными - читать, преобразовывать и сохранять

 ## Установка

 ```
 conda install pandas
 ```

In [60]:
import pandas as pd

## Series

Series - столбец в таблице.

Он состоит из индекса ("имена" строк) и значений. По-умолчанию индекс - уникальные числа от 0 до длины списка.

Создавать series можно из списка или массива numpy. 

In [61]:
series = pd.Series([1, 2, 3])
series

0    1
1    2
2    3
dtype: int64

In [62]:
series.index

RangeIndex(start=0, stop=3, step=1)

In [63]:
series.values

array([1, 2, 3])

Индекс может быть строкой

In [64]:
legs_counter = pd.Series([4, 4, 8], index=["cat", "dog", "spider"])
legs_counter

cat       4
dog       4
spider    8
dtype: int64

По series можно индексирования при помощи `loc` и `iloc`

- `loc` - если хотим взять по индексу
- `iloc` - если хотим взять по порядковому номеру

In [65]:
legs_counter.iloc[2]

8

In [66]:
legs_counter.loc["dog"]

4

In [67]:
legs_counter.unique()

array([4, 8])

## DataFrame

DataFrame - набор Series, то есть таблица.

Индекс для датафрейма - названия строк

Колонки - названия столбцов (series)

In [68]:
ages = [25, 35, 45]
heights = [170, 180, 190]
names = ["Alex", "Polina", "Misha"]
data = {'age': ages, 'height': heights, 'name': names}
df = pd.DataFrame(data)
df

age  height    name
0   25     170    Alex
1   35     180  Polina
2   45     190   Misha

In [69]:
df['age']  #Получился Series

0    25
1    35
2    45
Name: age, dtype: int64

In [70]:
df[['age', 'height']] #Получился DataFrame

age  height
0   25     170
1   35     180
2   45     190

In [71]:
df[['age']] # Получился DataFrame

age
0   25
1   35
2   45

Можно добавить новую колонку

In [72]:
df['height/age'] = df['height'] / df['age']
df

age  height    name  height/age
0   25     170    Alex    6.800000
1   35     180  Polina    5.142857
2   45     190   Misha    4.222222

In [73]:
df["age"].sum()
df["age"].min()
df["age"].max()
df["age"].mean()

35.0

Можно взять содержимое датафрейма как набор numpy-массивов

In [74]:
df.values

array([[25, 170, 'Alex', 6.8],
       [35, 180, 'Polina', 5.142857142857143],
       [45, 190, 'Misha', 4.222222222222222]], dtype=object)

Можно фильтровать датафреймы

In [75]:
df[df['age'] == 25]

age  height  name  height/age
0   25     170  Alex         6.8

In [76]:
df[(df['age'] > 35) & (df['height'] > 170)]

age  height   name  height/age
2   45     190  Misha    4.222222

Если нужно поменять какое-то значение, можно использовать [.loc](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy)

In [77]:
df.loc[df['age'] == 25, 'age'] = 20

In [78]:
df[df['height/age'] > 5]

age  height    name  height/age
0   20     170    Alex    6.800000
1   35     180  Polina    5.142857

Создадим категорию "высокий", если человек выше 175, а иначе "низкий"

In [79]:
df["height_category"] = df["height"].apply(lambda x: "высокий" if x > 175 else "низкий")
df

age  height    name  height/age height_category
0   20     170    Alex    6.800000          низкий
1   35     180  Polina    5.142857         высокий
2   45     190   Misha    4.222222         высокий

In [80]:
df[(df['height_category'] == "высокий") & (df['age'] > 40)]

age  height   name  height/age height_category
2   45     190  Misha    4.222222         высокий

## Задача

Посчитать средний рост для высоких людей

In [81]:
# Ваш код здесь


## Пропуски в данных

Часто в реальных данных есть пропуски. Их надо либо убирать, либо заполнять

In [82]:
values = [[None, 1, 2], [None, 2, 3], [None, None, 4]]
df = pd.DataFrame(values, columns=["a", "b", "c"])
df

a    b  c
0  None  1.0  2
1  None  2.0  3
2  None  NaN  4

За удаление отвечает функция `dropna()`

У dropna есть два важных аргумента:

- axis (по-умолчанию 0) - по строкам или по колонкам будем искать наны
- how (по-умолчанию 'any') - бывает any и all, ниже пример использования

Удаляем столбец `a`, потому что в нем все (all) значения None

Сохраним датафрейм, он понадобится ниже

In [83]:
dropped_a = df.dropna(axis=1, how='all')
dropped_a

b  c
0  1.0  2
1  2.0  3
2  NaN  4

Удаляем столбцы `a` и `b`, потому что в них есть None (any)

In [84]:
df.dropna(axis=1, how='any')

c
0  2
1  3
2  4

Возьмем датафрейм выше. Удалим из него последнюю строку, так как в ней есть None

In [85]:
dropped_a.dropna(axis=0, how='any')

b  c
0  1.0  2
1  2.0  3

Заполним пустые значения 0

In [86]:
df.fillna(0)

a    b  c
0  0  1.0  2
1  0  2.0  3
2  0  0.0  4

Заполним последним известным значением

In [87]:
df.fillna(method="ffill")
# Тоже самое, что и df.ffill()

a    b  c
0  None  1.0  2
1  None  2.0  3
2  None  2.0  4

Заполним средним между соседними известными значениями

In [88]:
df.interpolate()

a    b  c
0  None  1.0  2
1  None  2.0  3
2  None  2.0  4

## Работаем с данными

Мы можем прочитать таблицу из разных форматов: Excel, CSV, TSV, HDF и т.д.

Начнем с самого простого формата - CSV. Можно открыть в блокноте файл `data/weather.csv` и посмотреть как он выглядит.

Чтобы загрузить файл в DataFrame, воспользуемся методом `pd.read_csv()`

In [89]:
df = pd.read_csv('../data/weather.csv')
df.head()

Day   t
0  2008-01-01   0
1  2008-01-02  -5
2  2008-01-03 -11
3  2008-01-04 -11
4  2008-01-05 -12

In [90]:
df.describe()

t
count  3285.000000
mean      8.137595
std      10.403138
min     -23.000000
25%       1.000000
50%       8.000000
75%      17.000000
max      34.000000

In [91]:
df["Day"] = pd.to_datetime(df["Day"])
df["year"] = df.Day.dt.year
df["month"] = df.Day.dt.month
df["day"] = df.Day.dt.day
df.head()

Day   t  year  month  day
0 2008-01-01   0  2008      1    1
1 2008-01-02  -5  2008      1    2
2 2008-01-03 -11  2008      1    3
3 2008-01-04 -11  2008      1    4
4 2008-01-05 -12  2008      1    5

## Задача

Вывести среднюю температуру за январь 2010 года

In [92]:
# Ваш код здесь


## Группировка и агрегация данных

Иногда нужно объединять строки, в которых есть какие-то одинаковые значения.

Например, мы хотим посчитать среднюю температуру для каждого месяца. Это значит, что нам нужны строки, в которых совпадают year и month

In [116]:
for name, group in df.groupby(["year", "month"]):
    print(name)
    print(group.head(2))
    break

(2008, 1)
         Day  t  year  month  day month_name   T_f
0 2008-01-01  0  2008      1    1     Январь  32.0
1 2008-01-02 -5  2008      1    2     Январь  23.0


In [117]:
df.groupby(["year", "month"]).mean()

t        day        T_f
year month                                 
2008 1      -1.612903  16.000000  29.096774
     2       0.034483  15.000000  32.062069
     3       1.516129  16.000000  34.729032
     4       9.566667  15.500000  49.220000
     5      14.133333  16.333333  57.440000
...               ...        ...        ...
2016 8      19.161290  16.000000  66.490323
     9      14.366667  15.500000  57.860000
     10      5.870968  16.000000  42.567742
     11     -1.433333  15.500000  29.420000
     12     -0.806452  16.000000  30.548387

[108 rows x 3 columns]

Вопрос - почему среднее по дням разное?

Иногда мы хотим применить какую-то функцию, которой нет в стандартном pandas или хотим применить много разных функций к определенным строкам. Для этого существует метод agg (сокращение от Aggregate)

In [121]:
df.groupby(["month"]).agg(['mean', 'max', 'std']) # Применяем много функций ко всем столбцам

t                       year                        day      \
            mean max       std         mean   max       std       mean max   
month                                                                        
1      -5.745520   5  6.316853  2012.000000  2016  2.586629  16.000000  31   
2      -3.505882   6  5.953805  2012.000000  2016  2.596181  14.670588  29   
3       0.759857  13  4.252342  2012.000000  2016  2.586629  16.000000  31   
4       7.744444  21  4.167214  2012.000000  2016  2.586784  15.500000  30   
5      15.291367  30  5.149533  2012.014388  2016  2.580084  16.035971  31   
6      18.325926  31  4.513227  2012.000000  2016  2.586784  15.500000  30   
7      21.949640  33  4.418249  2012.003597  2016  2.590594  15.946043  31   
8      19.666667  34  4.102114  2012.000000  2016  2.586629  16.000000  31   
9      14.574074  24  3.318316  2012.000000  2016  2.586784  15.500000  30   
10      7.326165  16  3.501962  2012.000000  2016  2.586629  16.000000  31   
11      2.466667  11  4.134001  2012.000000  2016  2.586784  15.500000  30   
12     -1.823741   8  5.425692  2012.000000  2016  2.591293  16.000000  31   

                       T_f                   
            std       mean   max        std  
month                                        
1      8.960344  21.658065  41.0  11.370336  
2      8.196967  25.689412  42.8  10.716850  
3      8.960344  33.367742  55.4   7.654215  
4      8.671515  45.940000  69.8   7.500986  
5      8.956300  59.524460  86.0   9.269159  
6      8.671515  64.986667  87.8   8.123808  
7      8.930981  71.509353  91.4   7.952847  
8      8.960344  67.400000  93.2   7.383805  
9      8.671515  58.233333  75.2   5.972969  
10     8.960344  45.187097  60.8   6.303531  
11     8.671515  36.440000  51.8   7.441201  
12     8.976504  28.717266  46.4   9.766246

In [123]:
# применяем много функций к определенным столбцам
df.groupby(["month"]).agg({'t':['count','mean','max','min'],'day':['mean']}) 

t                           day
      count       mean max min       mean
month                                    
1       279  -5.745520   5 -21  16.000000
2       255  -3.505882   6 -23  14.670588
3       279   0.759857  13 -11  16.000000
4       270   7.744444  21  -1  15.500000
5       278  15.291367  30   3  16.035971
6       270  18.325926  31   9  15.500000
7       278  21.949640  33  12  15.946043
8       279  19.666667  34  10  16.000000
9       270  14.574074  24   5  15.500000
10      279   7.326165  16  -2  16.000000
11      270   2.466667  11 -13  15.500000
12      278  -1.823741   8 -19  16.000000

In [127]:
df.groupby(["month"]).agg(
    {'t':[
        ('one',  np.mean), 
        ('two', lambda value: 100 * ((value>32).sum() / value.std())), 
        ('three', lambda value: 100* ((value > 45).sum() / value.mean()))
    ]}
)

t                 
             one        two three
month                            
1      -5.745520   0.000000  -0.0
2      -3.505882   0.000000  -0.0
3       0.759857   0.000000   0.0
4       7.744444   0.000000   0.0
5      15.291367   0.000000   0.0
6      18.325926   0.000000   0.0
7      21.949640  22.633403   0.0
8      19.666667  24.377675   0.0
9      14.574074   0.000000   0.0
10      7.326165   0.000000   0.0
11      2.466667   0.000000   0.0
12     -1.823741   0.000000  -0.0

## Функция map

In [95]:
month_number_to_name = {
    1: "Январь",
    2: "Февраль",
    3: "Март",
    4: "Апрель",
    5: "Май",
    6: "Июнь",
    7: "Июль",
    8: "Август",
    9: "Сентябрь",
    10: "Октябрь",
    11: "Ноябрь",
    12: "Декабрь"
}

In [96]:
df["month_name"] = df["month"].map(month_number_to_name)
df.head()

Day   t  year  month  day month_name
0 2008-01-01   0  2008      1    1     Январь
1 2008-01-02  -5  2008      1    2     Январь
2 2008-01-03 -11  2008      1    3     Январь
3 2008-01-04 -11  2008      1    4     Январь
4 2008-01-05 -12  2008      1    5     Январь

Сохраним результаты

## Функций apply

In [97]:
df['T_f'] = df.t.apply(lambda x: 9/5 * x + 32)
df.head()

Day   t  year  month  day month_name   T_f
0 2008-01-01   0  2008      1    1     Январь  32.0
1 2008-01-02  -5  2008      1    2     Январь  23.0
2 2008-01-03 -11  2008      1    3     Январь  12.2
3 2008-01-04 -11  2008      1    4     Январь  12.2
4 2008-01-05 -12  2008      1    5     Январь  10.4

In [98]:
df.to_csv('result.csv')

## Задача

**Во всех задачах ниже стараемся избегать циклов**


Найти насколько отличалась температура в самый жаркий и самый холодный день

## Задача

Вывести среднее, максимальное, минимальное, стандартное отклонение и медиану температуры за каждый год

## Задача

Необходимо узнать насколько медиана отличалась от среднего в каждом месяце. Использовать agg для решения

## Задача

Вывести день, в который максимально изменилась температура

Подсказка: `diff()`

In [99]:
# Ваш код здесь


## Поработаем с экселем

Сохраним датафрейм в эксель

In [100]:
df.to_excel('../data/excel.xlsx')

Прочитаем из экселя

In [101]:
pd.read_excel('../data/excel.xlsx', index_col=0)

Day   t  year  month  day month_name   T_f
0    2008-01-01   0  2008      1    1     Январь  32.0
1    2008-01-02  -5  2008      1    2     Январь  23.0
2    2008-01-03 -11  2008      1    3     Январь  12.2
3    2008-01-04 -11  2008      1    4     Январь  12.2
4    2008-01-05 -12  2008      1    5     Январь  10.4
...         ...  ..   ...    ...  ...        ...   ...
3280 2016-12-27   1  2016     12   27    Декабрь  33.8
3281 2016-12-28  -3  2016     12   28    Декабрь  26.6
3282 2016-12-29   0  2016     12   29    Декабрь  32.0
3283 2016-12-30   3  2016     12   30    Декабрь  37.4
3284 2016-12-31   4  2016     12   31    Декабрь  39.2

[3285 rows x 7 columns]

# Полезные ссылки

- [Git](https://git-scm.com/downloads)

- [Anaconda](https://www.anaconda.com/products/individual#Downloads)

- [VS Code](https://code.visualstudio.com/download)

- [Шпаргалка по анаконде](https://docs.conda.io/projects/conda/en/4.6.0/_downloads/52a95608c49671267e40c689e0bc00ca/conda-cheatsheet.pdf)

- [Шпаргалка по гиту](https://education.github.com/git-cheat-sheet-education.pdf)

- [Установка jupyterlab (вариант с conda install, не забываем активировать окружение)](https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html)

- [Небольшой курс по numpy-pandas-matplotlib, если хочется интерактивных задач](https://www.sololearn.com/learning/1161)

# Домашняя работа

## Easy

Открыть набор данных dota_hero_stats.csv из папки data. 

Данные взяты [отсюда](https://api.opendota.com/api/heroes), на этом же [сайте](https://www.opendota.com/) можно найти больше разнообразных данных по Dota2.

Пересчитаем число ног у героев игры Dota2! Сгруппируйте героев из датасэта по числу их ног (колонка legs), и посчитайте количество героев для каждого значения legs

## Normal

Продолжим исследование героев Dota2. Сгруппируйте по колонкам attack_type и primary_attr и выберите самый распространённый набор характеристик. Выведите список героев с этим набором характеристик


## Hard

В колонке roles находится список того, к каким ролям приписывают создатели Dota того или иного героя. 
Так же у каждого героя есть его основная характеристика, которая записана в колонке primary_attr.

1) Для каждой роли требуется построить bar plot на котором будет видно какое колличество раз героев с тем или иным основным атрибутам создатели игры относят к данной роли.

2) Так же требуется сделать обратный график: для каждого основного аттрибута сделайте bar plot на котором будет видно какое колличество раз создатели Dota относили героя с этим атрибутом к конкретной роли.

3) Сделайте выводы по полученым графикам (это могут быть совершенно любые выводы)

P.s
Для задания 1 должно получится 12 таких графиков (для каждой роли):

![screen 1](https://raw.githubusercontent.com/Shakirov-ER/brunoyam-ds-SC372-2560/main/images/02-screenshot_1.png)

Для задания 2 должно получится 3 таких графика (для каждого атрибута): 

![screen 2](https://raw.githubusercontent.com/Shakirov-ER/brunoyam-ds-SC372-2560/main/images/02-screenshot_2.png)

p.s.s Задание непростое. Попробуйте сначала сделать сами. Если не получается, то в ноутбуке 02-solution есть подсказка